### ISSUE TITLE
[LFT] Fullstack JS dev looking for fun project

### ISSUE THREAD

**Issue by maggo** [ethberlinzwei/Find-A-Team#14]
## Background

Hi, I'm Marco, fullstack JS developer from Berlin. After hearing the legends about Ethereum hackathons I decided to join one and here we are! I've been playing around with web3 for a while now, mostly on the client side but also got my backend experience while developing an MVP last year to combine traditional centralized services and blockchain.

I'm hoping to find a chill project to develop something fun, say a new meme token with some crazy interactivity? Or something that can put blockchain in your day to day life? Of course I'm open to all kinds of ideas, so let me know what you've planned!

## Skills

- [x] React and traditional web tech
- [x] web3/ethers
- [x] next.js for backend
- [x] An eye for UX and DX

## Communication

Riot: muchwin
Twitter: [@mediaquery](https://twitter.com/mediaquery)

**Comment by kapulkin** [comment]
We are creating fast prediction market on Ethereum side-chain, which could be used in real product at #21.

Would you like to join us?

**Comment by maggo** [comment]
Thanks for contacting me, but I found a project already :) Good luck!
