### ISSUE TITLE
[LFT] iOS, some web dev, UX, documentation and structure

### ISSUE THREAD

**Issue by gubikmic** [ethberlinzwei/Find-A-Team#16]
### Background

Broad background. Studied mathematics but also some psychology. I’m looking at UX more from a functional perspective. I think UX is extremely important and often quite lacking. Here to help improve that.
Experience in iOS and Swift and also a little experience with JavaScript and React. Played around with web3.

### Skills
- [x] User Experience
- [x] iOS and Swift
- [x] Web3.JS (JavaScript, CSS)
- [x] Project Management

### Communication

- [x] _Riot handle_: gubikmic
- [ ] _Status IM_:

**Comment by gubikmic** [comment]
I’d also be interested in dev tools for smart contracts (and other things) but probably way too little time to start learning that during a hackathon. Don’t hesitate to message me

**Comment by chrishobcroft** [comment]
This: https://github.com/ethberlinzwei/Find-A-Team/issues/25

Or this: https://github.com/ethberlinzwei/Find-A-Team/issues/26

?

**Comment by aquabu** [comment]
Hi @gubikmic would love to hack with you on #36 : a proposal-less "Virtue DAO" that funds a swarm of autonomous contributors based on their virtue. Your UX advocacy would be really helpful for developing and sharing this DAO approach to non-technical people.

Message me on issue #36 or on telegram @noahthorp
