### ISSUE TITLE
[LFT] Data Scientist looking for a team

### ISSUE THREAD

**Issue by mtagda** [ethberlinzwei/Find-A-Team#22]
## Background

- [ ] _Who you are_: Magdalena Trzeciak
- [ ] _What you do_: I'm a Data Scientist, passionate about AI 
- [ ] _How you got first into Ethereum_: Buying some ETH :) 
- [ ] _What brings you to ETHBerlin_: Want to learn more about the ETH world

## Skills

_Tell us what your skills are:_

- [ ] Data Science
- [ ] Python
- [ ] AI
- [ ] Databases

## Communication
https://www.linkedin.com/in/mtagda

**Comment by chrishobcroft** [comment]
I would like to discuss this with you: https://github.com/ethberlinzwei/Find-A-Team/issues/19

Are you interested?

**Comment by chrishobcroft** [comment]
Also, do you know anything about Speech Recognition?

It's an AI / Big Data kinda problem.

https://github.com/ethberlinzwei/Find-A-Team/issues/28

**Comment by mtagda** [comment]
Hi Chris!
I'm interested! And yes, I'm familiar with the topic of Speech Recognition.
Could you give me some details on the problem to solve? Sounds very
interesting!

**Comment by chrishobcroft** [comment]
@mtagda I left a comment on the issue.

**Comment by mtagda** [comment]
@chrishobcroft thanks! I'm interested, would like to join! :)

**Comment by chrishobcroft** [comment]
OK, so we are a team of 2. Please can you indicate this on Github, so they upgrade our proposal.
