### ISSUE TITLE
[LFT] Software/smart contract developer with some ZKP experience

### ISSUE THREAD

**Issue by mariogemoll** [ethberlinzwei/Find-A-Team#30]
## Background

Hi!

I've been working professionally as a software developer for many years and for about two and a half years in an dev agency for blockchain projects, mostly on smart contract and backend bits for Ethereum projects.

The last couple of months I've been investigating zero-knowledge proofs and built a prototype of a Zerocash implementation for Ethereum (and Fabric), similar to ZEth and Nightfall: https://github.com/appliedblockchain/k0

Given my background I can help with all parts of a DApp project: **Solidity smart contracts**, **server backends** (if needed) in JavaScript, Clojure, Python, Java, Go etc, **JavaScript browser code** and also UI (although haven't done much UI work lately). I can also help code **zkSNARK** circuits in libsnark/gadgetlib1/C++.

This is my first hackathon. And of course also my first ETH Berlin, but I heard a lot of good things about the event last year so I'm thrilled to be part of it and looking forward to meeting many interesting people and hopefully to work on an exciting project.

## Skills

- [ ] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [ ] Design, User Experience
- [ ] Project Management
- [ ] Game theory
- [x] _Other_: backend server apps, some zkSNARKs experience

## Communication

- [x] _Riot handle_: @mariogemoll:matrix.org
- [x] _Telegram handle_: @mariogemoll
- [ ] _Status IM_

**Comment by kapulkin** [comment]
Me ant teammate are thinking about making insurance service based on fast prediction market at #21. ZKP could allow insurance companies to make decisions without accessing to sensitive data of the consumer. 

Would you like to join?

**Comment by mariogemoll** [comment]
Hey @kapulkin thanks, see chat on Telegram

**Comment by aquabu** [comment]
Hi @mariogemoll although not ZKP, I would love to hack with you on #36 : a proposal-less "Virtue DAO" that funds a swarm of autonomous contributors based on their virtue. Message me on issue #36 or on telegram @noahthorp

**Comment by acrdlph** [comment]
Something more down-to-earth ;) https://github.com/ethberlinzwei/Find-A-Team/issues/44
