### ISSUE TITLE
UX/UI designer looking for a team!

### ISSUE THREAD

**Issue by bennisan86** [ethberlinzwei/Find-A-Team#31]
## Background
Hi all! I'm Ben a.k.a. Bennisan (known to the [Swarm City](https://github.com/swarmcity) folk as [Faffy Diggins](https://github.com/faffydee)), I'm a UX/UI designer, happily working in the blockchain-space since 2016 (check out my [portofolio](behance.net/bennisan))!

_Some background:_
Graduated in 2008 as a graphic designer with a passion for all things digital. Ran away screaming from the advertising business after a couple of years, and since then aiming to use my skills to create an added value for society/humanity. Came across blockchain-tech in 2015 and saw this as the best way to reach this goal.

I firmly believe blockchain-tech is the future and could solve a lot of current problems we're facing as a society. Now let's roll up the ol' sleeves and get this mass-adoption thing going by creating useful and easy-to-use applications!

_What I do and love:_
UX/UI, branding, html&css, illustration, explainers, external communication...
Contact me here or in Riot!

## Skills
- [x] Design, User Experience
- [x] Branding, communication
- [x] Illustration, explainer-videos
- [x] html, css

## Communication
- [x] _Riot handle_: @bennisan:matrix.org

**Comment by chrishobcroft** [comment]
How about:

https://github.com/ethberlinzwei/Find-A-Team/issues/26

Or...

https://github.com/ethberlinzwei/Find-A-Team/issues/25

**Comment by bennisan86** [comment]
yeah @chrishobcroft , #25 looks cool! I could go for that. Is there anyone else involved so far?

**Comment by chrishobcroft** [comment]
Perhaps comment on #25 so that other people can see that you are interested.

Also, perhaps ask a question in the comments?

**Comment by acrdlph** [comment]
useful, easy to use and solving a clear real-world problem: https://github.com/ethberlinzwei/Find-A-Team/issues/44

**Comment by aquabu** [comment]
Hi @bennisan86  would love to hack with you on #36 : a proposal-less "Virtue DAO" that funds a swarm of autonomous contributors based on their virtue. UX/UI are quite important for developing the use case and making it easy to understand and use for non-blockchain folks. Message me here, on issue #36 or on telegram @noahthorp

**Comment by chrishobcroft** [comment]
Actively recruiting UX/UI for a project with 1 developer already attached

https://github.com/ethberlinzwei/Find-A-Team/issues/48

**Comment by ghost** [comment]
I am up for helping and working together, where are you guys ?

**Comment by chrishobcroft** [comment]
Hi @ClaireDesombre - did you find the team? Did you find a project?

**Comment by ghost** [comment]
Thank you for your answer back!
No I didn’t. I thinks now all are cooked
 So ... next hackathon! But if u Need flesh eyes on ux design just text me and I come to help;)

_________________________________________
Claire Desombre - 0695443431 -
Linkedin - Viadéo

**Comment by bennisan86** [comment]
You guys are really misusing my issue here :-D! And @ClaireDesombre , I will definitely reach out if I need flesh eyes, or in case of overcooked teams :-D
