### ISSUE TITLE
[LFT] Full-stack/Blockchain engineer

### ISSUE THREAD

**Issue by wslyvh** [ethberlinzwei/Find-A-Team#32]
## Background

My name is Wesley from Amsterdam, the Netherlands. +10 years of experience in enterprise software development & delivery. In the blockchain space now for about 3 years. Graduate on the first ConsenSys academy, and alumni. Currently working as freelance blockchain tech lead and founder of the blockchain Netherlands foundation. 

I've seen most roles in an IT/software organization and quite versatile in terms of roles/skills.

I was mentor at ETH Berlin last year, but looking forward to build something again. Try and learn new things. Meeting new people, keeping up my coding skills. 

And have some fun ! 

## Skills

Full-stack, MERN , or C#/.NET, blockchain, Solidity, DevOps, infra. 
- wouldn't mind to learn Go, or Python 

- [ ] Core Blockchain Development (Go, C++, Rust) 
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (TypeScript, React, Node, JavaScript, CSS)
- [x] Design, User Experience
- [x] Project Management
- [x] _Other_: C#, ASP.NET 
Infrastructure, DevOps 

## Communication

- [x] _Riot handle_: wslyvh 
- [x] _Status IM_: wslyvh
- [x] _telegram_: wslyvh 

https://www.twitter.com/wslyvh
http://linkedin.com/in/WesleyvanHeije/

**Comment by kapulkin** [comment]
I would like to suggest you join to #21 

Are you interested?

**Comment by tobias-kaiser** [comment]
I am still looking for a blockchain engineer / UI dev in #18.

**Comment by aquabu** [comment]
Hi @wslyvh would love to hack with you on #36 : a proposal-less "Virtue DAO" that funds a swarm of autonomous contributors based on their virtue. Message me on issue #36 or on telegram @noahthorp

**Comment by acrdlph** [comment]
Join us if you want to work on the intersection of public transport, social media and blockchain: https://github.com/ethberlinzwei/Find-A-Team/issues/44

**Comment by wslyvh** [comment]
Going to work on #25. Others are welcome to join!
