### ISSUE TITLE
[LFT] solidity developer, good react knowledge. Built full DApps in other hackathons

### ISSUE THREAD

**Issue by vibern0** [ethberlinzwei/Find-A-Team#45]
## Background

_Talk a little about yourself:_

Hi, my name is Bernardo.
I work in a consultancy startup as blockchain developer for a year now. I've joined a few blockchain hackathons and succeed in some.

Back in 2017 I was in Lisbon in an Hackathon when I first heard about ethereum. Loved it so much that decided to start exploring.

Since then I've contributed to a number of ethereum related projects as well as some other blockchain projects.

It's my first time in Berlin and I want to come here because I want to meet more people, and also because a bird told me that things here were crazy. I had to try :man_shrugging: 

I'm here to build real stuff to improve people's like. Let's talk :speaking_head: 

## Skills

_Tell us what your skills are:_

- [ ] Core Blockchain Development (Go, C++, Rust)
- [x] Smart Contracts (Solidity, Vyper)
- [x] DApps, Web3.JS (JavaScript, CSS)
- [ ] Design, User Experience
- [x] Project Management
- [ ] Game theory
- [x] _Other_: memes

## Communition

- [ ] _Riot handle_: obernardovieira
- [ ] _Status IM_: obernardovieira

**Comment by acrdlph** [comment]
improve people's likes and lives: https://github.com/ethberlinzwei/Find-A-Team/issues/44

**Comment by wslyvh** [comment]
Join us to take a human-centric approach on managing your DAO's 
#25
